blank_issues_enabled: false
contact_links:
  - name: Question d'utilisation
    url: https://github.com/McSon2/Sofafin/discussions
    about: Pour tout ce qui n'est ni une anomalie ni une proposition.
